### ISSUE TITLE
Next major v15

### ISSUE THREAD

**Issue by teppeis** [teppeis/eslint-config-teppeis#642]
## Deps
- Support ESLint v8
  - [x] eslint: https://github.com/teppeis/eslint-config-teppeis/pull/611
  - [x] typescript: https://github.com/teppeis/eslint-config-teppeis/pull/638
  - [x] unicorn: https://github.com/teppeis/eslint-config-teppeis/pull/644
  - [x] import: https://github.com/teppeis/eslint-config-teppeis/pull/639
  - [x] jsdoc: https://github.com/gajus/eslint-plugin-jsdoc/issues/791 At least `checkExample` uses `CLIEngine`.
  - [ ] comments: https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/62
    - only dev/test
  - [ ] node: https://github.com/mysticatea/eslint-plugin-node/issues/294 only dev/test
    - only dev/test
  - [x] https://github.com/teppeis/eslint-config-teppeis/issues/574
- <del>Node.js: ^12.20, ^14.14, or 16</del>
  - <del>jsdoc v36 https://github.com/gajus/eslint-plugin-jsdoc/releases/v36.0.0, https://github.com/gajus/eslint-plugin-jsdoc/releases/v36.0.1<del>
  - [x] https://github.com/gajus/eslint-plugin-jsdoc/issues/774

## Rules

- [x] [`import/no-unresolved`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md): enable `caseSensitiveStrict` option (#639)
  - https://github.com/teppeis/eslint-config-teppeis/pull/652
- [x] https://github.com/teppeis/eslint-config-teppeis/pull/656
- [x] #658 

## TypeScript 4.5

- [x] https://github.com/typescript-eslint/typescript-eslint/issues/3950
- [ ] https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/83
- [x] [Prettier 2.5: TypeScript 4.5 and MDX v2 comment syntax! · Prettier](https://prettier.io/blog/2021/11/25/2.5.0.html)

## Node v16

- [x] Add `node-v16` config that ignores `node/no-unsupported-features`: https://github.com/teppeis/eslint-config-teppeis/pull/663

**Comment by teppeis** [comment]
released https://github.com/teppeis/eslint-config-teppeis/releases/tag/v15.0.0

**Comment by teppeis** [comment]
released
https://github.com/alexgorbatchev/eslint-import-resolver-typescript/releases/tag/v2.7.0
