### ISSUE TITLE
v6.0

### ISSUE THREAD

**Issue by teppeis** [teppeis/eslint-config-teppeis#65]
### Breaking changes
- [x] [eslint@4](http://qiita.com/mysticatea/items/3d01452d76ea6c943793) #72
  - `indent`: enable `MemberExpression`
  - enable added recommended rules
    - `no-compare-neg-zero`
    - `no-useless-escape`
- [x] [eslint-plugin-node@5](https://github.com/mysticatea/eslint-plugin-node/releases) #71
- [x] add `{unnecessary: false}` to `quote-props b63ea7a
- enable rules #73
  - [x] `comma-dangle`
- disable rules #73
  - [x] `no-magic-numbers`
  - [x] `no-console`
  - [x] `no-sync`
  - [x] `consistent-return`
- from error to warn #73
  - [x] `max-len`
  - [x] `max-depth`
  - [x] `max-nested-callbacks`
  - [x] `max-params`
  - [x] `max-statements`
- [x] rename es6 with es2015 #74
- [x] move to CircleCI 2.0 #75
- [x] add `node-v8` #76
- [x] add new `es2017` globals #76
- [x] remove `env.browser` by default #77
- [x] revise all rules #77
